//
//  FlatIcons.h
//  FoodPiper
//
//  Created by (null) on 12/5/15.
//  Copyright (c) 2015 Dephyned. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface FlatIcons : NSObject

// Drawing Methods
+ (void)drawCarIconWithFrame: (CGRect)frame;
+ (void)drawAddressIconWithFrame: (CGRect)frame;

@end
