//
//  FlatIcons.m
//  FoodPiper
//
//  Created by (null) on 12/5/15.
//  Copyright (c) 2015 Dephyned. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "FlatIcons.h"


@implementation FlatIcons

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawCarIconWithFrame: (CGRect)frame
{
    //// Color Declarations
    UIColor* fillColor = [UIColor colorWithRed: 0.961 green: 0.639 blue: 0.184 alpha: 1];


    //// Subframes
    CGRect car80svgGroup = CGRectMake(CGRectGetMinX(frame), CGRectGetMinY(frame) + 0.37, CGRectGetWidth(frame) - 0.35, CGRectGetHeight(frame) - 0.09);


    //// car80.svg Group
    {
        //// Group 2
        {
            //// Bezier Drawing
            UIBezierPath* bezierPath = [UIBezierPath bezierPath];
            [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.99999 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.55548 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.98753 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.48833 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.99999 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.53175 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.99555 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.50907 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.98457 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.47245 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.98670 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.48305 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.98575 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.47779 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.89771 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.21264 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.89712 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.21030 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.71383 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.00000 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.86673 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.10108 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.82349 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.00000 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.29458 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.00000 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.11146 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.20969 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.18222 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.00000 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.14252 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.10359 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.02060 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.47014 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.00000 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.55548 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.00747 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.49554 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.00000 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.52459 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.00000 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.63633 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.00355 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.67283 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.00000 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.64883 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.00122 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.66106 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.00000 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.69570 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.00129 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.67995 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.00000 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.68762 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.00000 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.93615 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.05290 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 1.00000 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.00000 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.97141 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.02368 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 1.00000 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.16267 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 1.00000 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.21556 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.93615 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.19187 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 1.00000 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.21556 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.97141 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.21556 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.81591 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.79070 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.81591 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.79070 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.93615 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.84361 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 1.00000 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.79070 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.97141 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.81439 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 1.00000 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.94709 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 1.00000 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 1.00000 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.93615 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.97632 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 1.00000 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 1.00000 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.97141 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 1.00000 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.69567 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.99645 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.67282 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 1.00000 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.68762 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.99870 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.67992 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 1.00000 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.63632 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.99877 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.66103 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 1.00000 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.64882 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 1.00000 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.55549 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.99999 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.55549 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.99999 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.55548 * CGRectGetHeight(car80svgGroup))];
            [bezierPath closePath];
            [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.17593 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.23578 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.29458 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.08205 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.21052 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.11800 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.23833 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.08205 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.71381 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.08205 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.83233 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.23527 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.76964 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.08205 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.80073 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.12215 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.89572 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.39030 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.82831 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.37592 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.87502 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.38105 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.85224 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.37592 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.17167 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.37592 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.11054 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.38767 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.15013 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.37592 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.12954 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.38010 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.17593 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.23578 * CGRectGetHeight(car80svgGroup))];
            [bezierPath closePath];
            [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.23038 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.66703 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.11456 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.66703 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.07679 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.62144 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.09370 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.66703 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.07679 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.64660 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.11456 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.57585 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.07679 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.59626 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.09370 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.57585 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.23038 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.57585 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.26816 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.62144 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.25124 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.57585 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.26816 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.59626 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.23038 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.66703 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.26816 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.64660 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.25123 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.66703 * CGRectGetHeight(car80svgGroup))];
            [bezierPath closePath];
            [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.63953 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.65790 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.37012 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.65790 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.34621 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.62904 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.35691 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.65790 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.34621 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.64498 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.37012 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.60016 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.34621 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.61308 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.35691 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.60016 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.63953 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.60016 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.66346 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.62904 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.65276 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.60016 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.66346 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.61308 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.63953 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.65790 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.66346 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.64498 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.65276 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.65790 * CGRectGetHeight(car80svgGroup))];
            [bezierPath closePath];
            [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.88251 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.66703 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.76669 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.66703 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.72891 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.62144 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.74582 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.66703 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.72891 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.64660 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.76669 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.57585 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.72891 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.59626 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.74583 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.57585 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.88251 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.57585 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.92030 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.62144 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.90338 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.57585 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.92030 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.59626 * CGRectGetHeight(car80svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.88251 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.66703 * CGRectGetHeight(car80svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.92030 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.64660 * CGRectGetHeight(car80svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(car80svgGroup) + 0.90338 * CGRectGetWidth(car80svgGroup), CGRectGetMinY(car80svgGroup) + 0.66703 * CGRectGetHeight(car80svgGroup))];
            [bezierPath closePath];
            bezierPath.miterLimit = 4;

            [fillColor setFill];
            [bezierPath fill];
        }


        //// Group 3
        {
        }


        //// Group 4
        {
        }


        //// Group 5
        {
        }


        //// Group 6
        {
        }


        //// Group 7
        {
        }


        //// Group 8
        {
        }


        //// Group 9
        {
        }


        //// Group 10
        {
        }


        //// Group 11
        {
        }


        //// Group 12
        {
        }


        //// Group 13
        {
        }


        //// Group 14
        {
        }


        //// Group 15
        {
        }


        //// Group 16
        {
        }


        //// Group 17
        {
        }
    }
}

+ (void)drawAddressIconWithFrame: (CGRect)frame
{
    //// Color Declarations
    UIColor* fillColor = [UIColor colorWithRed: 0.961 green: 0.639 blue: 0.184 alpha: 1];


    //// Subframes
    CGRect group = CGRectMake(CGRectGetMinX(frame), CGRectGetMinY(frame), CGRectGetWidth(frame), CGRectGetHeight(frame));


    //// Group
    {
        //// Group 2
        {
            //// Bezier Drawing
            UIBezierPath* bezierPath = [UIBezierPath bezierPath];
            [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.42500 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.38000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.36000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.02222 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.36900 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.36000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.01000 * CGRectGetHeight(group))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.36000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.23333 * CGRectGetHeight(group))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.18320 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.23333 * CGRectGetHeight(group))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.15485 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.23881 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.17494 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.23333 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.16470 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.23542 * CGRectGetHeight(group))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.12881 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.25194 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.14499 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.24217 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.13551 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.24682 * CGRectGetHeight(group))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.01006 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.34250 * CGRectGetHeight(group))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.36111 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.00335 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.34761 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.35437 * CGRectGetHeight(group))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.01006 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.37971 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.36786 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.00335 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.37458 * CGRectGetHeight(group))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.12881 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.47028 * CGRectGetHeight(group))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.15485 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.48342 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.13552 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.47539 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.14499 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.48004 * CGRectGetHeight(group))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.18320 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.48889 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.16471 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.48680 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.17495 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.48889 * CGRectGetHeight(group))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.36000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.48889 * CGRectGetHeight(group))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.36000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.97778 * CGRectGetHeight(group))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.38000 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.36000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99000 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.36900 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.42500 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.44500 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.97778 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.43600 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.44500 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99000 * CGRectGetHeight(group))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.44500 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.02222 * CGRectGetHeight(group))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.42500 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.44500 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.01000 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.43600 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
            [bezierPath closePath];
            [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.98993 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.23141 * CGRectGetHeight(group))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.87118 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.14083 * CGRectGetHeight(group))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.84514 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12768 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.86447 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.13571 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.85500 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.13107 * CGRectGetHeight(group))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.81679 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12222 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.83528 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12431 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.82504 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12222 * CGRectGetHeight(group))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.47500 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12222 * CGRectGetHeight(group))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.51503 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.37778 * CGRectGetHeight(group))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.81679 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.37778 * CGRectGetHeight(group))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.84514 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.37231 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.82504 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.37778 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.83529 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.37569 * CGRectGetHeight(group))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.87118 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.35918 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.85500 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.36894 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.86448 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.36429 * CGRectGetHeight(group))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.98993 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.26860 * CGRectGetHeight(group))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.25000 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.99664 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.26348 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.25676 * CGRectGetHeight(group))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.98993 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.23141 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.24326 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.99664 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.23652 * CGRectGetHeight(group))];
            [bezierPath closePath];
            bezierPath.miterLimit = 4;

            [fillColor setFill];
            [bezierPath fill];
        }
    }
}

@end
