//
//  FoodPiperIcons.h
//  FoodPiper
//
//  Created by Andrea Balcazar on 12/6/15.
//  Copyright (c) 2015 Dephyned. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface FoodPiperIcons : NSObject

// Drawing Methods
+ (void)drawCheckInIconWithFrame: (CGRect)frame;
+ (void)drawSendMessageIconWithFrame: (CGRect)frame;
+ (void)drawReservationIconWithFrame: (CGRect)frame;
+ (void)drawPipeIconWithFrame: (CGRect)frame;
+ (void)drawFavoriteIcon;
+ (void)drawHoursIconWithFrame: (CGRect)frame;
+ (void)drawMenuIcon;
+ (void)drawPhoneIconWithFrame: (CGRect)frame;
+ (void)drawStarFilledIconWithFrame: (CGRect)frame;
+ (void)drawStarEmptyIconWithFrame: (CGRect)frame;
+ (void)drawDoneIconWithFrame: (CGRect)frame;
+ (void)drawViewFavoritesIconWithFrame: (CGRect)frame;
+ (void)drawPeepIconWithFrame: (CGRect)frame;
+ (void)drawViewAllPeepsIconWithFrame: (CGRect)frame;
+ (void)drawFriendsIconWithFrame: (CGRect)frame;
+ (void)drawHotDealsIconWithFrame: (CGRect)frame;
+ (void)drawCameraIconWithFrame: (CGRect)frame;
+ (void)drawCommentIconWithFrame: (CGRect)frame;
+ (void)drawCrowdIconWithFrame: (CGRect)frame;
+ (void)drawDecorIconWithFrame: (CGRect)frame;
+ (void)drawServiceIcon;
+ (void)drawDealsIconWithFrame: (CGRect)frame;
+ (void)drawCancelIcon;
+ (void)drawStarHalfFilledIconWithFrame: (CGRect)frame;
+ (void)drawHalfFilledStarWithFrame: (CGRect)frame;
+ (void)drawCheckMarkIconWithFrame: (CGRect)frame;
+ (void)drawPasswordIconWithFrame: (CGRect)frame;
+ (void)drawUsernameIconWithFrame: (CGRect)frame;
+ (void)drawFastIconWithFrame: (CGRect)frame;
+ (void)drawMediumFastIconWithFrame: (CGRect)frame;
+ (void)drawSlowIconWithFrame: (CGRect)frame;
+ (void)drawCrowdSlowIconWithFrame: (CGRect)frame;
+ (void)drawCrowdGoodIcon;
+ (void)drawCrowdPackedIconWithFrame: (CGRect)frame;
+ (void)drawNotHotIconWithFrame: (CGRect)frame;
+ (void)drawSoSoIcon;
+ (void)drawHotIconWithFrame: (CGRect)frame;
+ (void)drawPercentOffIconWithFrame: (CGRect)frame;
+ (void)drawFreeIconWithFrame: (CGRect)frame;
+ (void)drawDollarOffIconWithFrame: (CGRect)frame;
+ (void)drawWebsiteIconWithFrame: (CGRect)frame;
+ (void)drawProfileIconWithFrame: (CGRect)frame;
+ (void)drawFriendsPipesIconWithFrame: (CGRect)frame;
+ (void)drawFoodIconWithFrame: (CGRect)frame;
+ (void)drawDirectionIconWithFrame: (CGRect)frame;
+ (void)drawShareIconWithFrame: (CGRect)frame;
+ (void)drawCancelSmallIcon;
+ (void)drawCancelIconLarge;
+ (void)drawFoodIconSmallWithFrame: (CGRect)frame;

@end
