//
//  FoodPiperLogo.h
//  FoodPiper
//
//  Created by Andrea Balcazar on 11/9/15.
//  Copyright (c) 2015 Dephyned. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface FoodPiperLogo : NSObject

// Drawing Methods
+ (void)drawLogoWithFrame: (CGRect)frame;

@end
