//
//  PaintCodeBackgrounds.h
//  FoodPiper
//
//  Created by Andrea Belcazar on 11/9/15.
//  Copyright (c) 2015 Dephyned. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface PaintCodeBackgrounds : NSObject

// Drawing Methods
+ (void)drawFoodBackgroundViewWithFrame: (CGRect)frame;
+ (void)drawCircularOrViewWithFrame: (CGRect)frame;

@end
